### ISSUE TITLE
Add more contents

### ISSUE THREAD

**Issue by ghost** [Samppaa/GTA-RP#11]
Hello guys,

How can i add contents like shop, works, house ... ?

Thanks in advance

**Comment by ghost** [comment]
@Samppaa ? Can you help me

**Comment by sjlehtonen** [comment]
ItemManager.cs has method "InitializeItemShops()", there you can see how shops are added and try to mimic it.

Houses are added in database, I will make guide later.

**Comment by ghost** [comment]
https://hastebin.com/egupacaqad.go
All the shops work, I just named the ones I added in the supermarket 1 - 6
If you want test, and update the github, as you want :)

**Comment by ghost** [comment]
More vehicle : 
https://hastebin.com/urapipimam.sql

**Comment by sjlehtonen** [comment]
Nice, I will add the shops on the next update, I checked and I need to adjust the coordinates a bit. Thanks

**Comment by ghost** [comment]
Trying to adjuste coordinates. I come back to you when its done

**Comment by ghost** [comment]
Coordinates have been uptated 
https://hastebin.com/aramovonok.go

The marker is a little in the air but I do not know how to put it on the ground

**Comment by ghost** [comment]
Can you tell me how I can add houses, as I give you the sql file once I've configured

**Comment by sjlehtonen** [comment]
Hi, I will write a detailed guide on creating new houses soon. But basically first you need to add a new building into the "buildings" table if needed. Then create new line in "house_template" table, and then create teleports in "house_teleports" and "house_exits" table, then link these in the "house_teleport_links"

You can try to look into these tables and see how I have done it. I will try to get the police faction done in the coming days, but I have much other work now too.

**Comment by ghost** [comment]
i've succeded to add somes house, i will give you soon the sql file

**Comment by ghost** [comment]
Hey bro,

tested and approved, enjoy :) 

https://hastebin.com/nonucurisa.sql

**Comment by sjlehtonen** [comment]
Looks good. Although when you try to enter the "Richards Majestic, Apt. 4", you will fall through the world so the exit point seems to be at wrong point. I imported them to the DB now so they will always be part of the releases. Same thing seems to happen with the Alta Street apartment

**Comment by ghost** [comment]
I will check when i’m at home

**Comment by ghost** [comment]
It works, you have to buy the houses
https://hastebin.com/ebaranujel.sql

**Comment by ghost** [comment]
Houses added
https://hastebin.com/ikarogehab.sql

**Comment by ghost** [comment]
How can i can more items ? like other weapons ?

**Comment by sjlehtonen** [comment]
Adding weapons should be quite easy. Just add rows to the table "item_templates", type 1 is weapon and the field1 is the weapon hash(these can be found at GT-MP wiki)

**Comment by ghost** [comment]
look at this 
https://gyazo.com/07c7b497acd57c1d67677748f15e5366?token=8a615a355875fcffdffaedfc5de76314
Idk why..

One more shop in ItemManager.cs

itemShops.Add(new ItemShop(14, "Scoops liquor barn", new Vector3(1165.73f, 2708.913f, 38.157f)));

I give you the coordinates of ammu-nations, it would be cool to separate stores and armory
some buildings do not open, so I put the coordinates in front and behind the door
https://hastebin.com/teyewofilo.pl

**Comment by sjlehtonen** [comment]
I have no idea about why the weapon bugs like that, might be something with the game.

I look into the shops later and try to finish the police faction soon but I had a lot of school and other work lately so it might take a little time. I also want to implement a fishing system when I have time for it, it shouldn't take long.

**Comment by sjlehtonen** [comment]
I created the initial jail system now and pushed the update. I add the updated houses and shops in the next update after I test them. I couldn't open the https://hastebin.com/ikarogehab.sql before but now I can apparently.

**Comment by ghost** [comment]
oh nice, it's ok for the hastebin file ?

**Comment by sjlehtonen** [comment]
It should be okay now, I will add those things in the next update.

**Comment by ghost** [comment]
more houses
https://hastebin.com/agohawacij.sql

**Comment by eodclan** [comment]
It contains a test account with name Test and password test123
Note: Your GTA-MP name must match the account name currently.
In the future, social club ID will be used instead.
It also contains a few characters on the account, their property ownerships and vehicle ownerships


OK and when is this social club ID function coming?

**Comment by sjlehtonen** [comment]
It's coming soon, possibly in the next update.

**Comment by eodclan** [comment]
Where do I change the login system?

**Comment by eodclan** [comment]
Which coordinates does the FIB house have? And can you bring this with you?
