### ISSUE TITLE
CONNECT IN COP SIDE

### ISSUE THREAD

**Issue by ghost** [Samppaa/GTA-RP#12]
Hello, 

When I put my character in "faction_id" 1. I am a lawyer but when I connect I am still in civilian clothes, however my rank at the bottom left has changed
Is it possible to connect as a police officer in this version? If yes, how ?

**Comment by ghost** [comment]
I have been looking for work at the point indicated, I have the status of employee but I can not work, or is the truck? how can I make it appear to start my work?

**Comment by sjlehtonen** [comment]
The police faction is not yet implemented, I will do it next when I have time.

If you are "Trash Collector", you need to spawn a truck with /spawnvehicle trash 1 1

Then when in the vehicle, use /startjob

I will implement more jobs when I have time, but I have been little busy recently.

**Comment by ghost** [comment]
ok thanks

**Comment by sjlehtonen** [comment]
I said wrong, when you are in the truck, you need to use /startjob to start the job

When I have time, I will create menus for starting the job etc.

**Comment by ghost** [comment]
ok thanks for infos
