### ISSUE TITLE
Database problem

### ISSUE THREAD

**Issue by KriZZeL** [Samppaa/GTA-RP#16]
Hey i have a problen i have imported your new sql file in my old that my users aren´t losing their money but they can´t login now the take this command /login [pw] but nothing happend after that... but a new registration isn´t possible because i deleted my character and Player in the database but still no work i have to login but my password isn´t in the database right now.... i become if i want to login an Error in the Error is to see  an mysql Failure... pls help

**Comment by KriZZeL** [comment]
The Error:
12:43:47.099 | Error | ScriptingEngine | EXCEPTION IN RESOURCE test INSIDE SCRIPTENGINE AdminCommands System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
   bei GTA_RP.Items.UseAnimationItem..ctor(Int32 id, String name, String description, Int32 entityId, Int32 bone, String other, Int32 count)
   bei GTA_RP.Items.ItemsFactory.CreateItemForTemplate(ItemTemplate template, Int32 amount)
   bei GTA_RP.Items.ItemManager.<>c__DisplayClass5.<LoadInventoryForCharacter>b__4(MySqlDataReader reader)
   bei GTA_RP.Database.SelectQuery.Execute()
   bei GTA_RP.PlayerManager.LoadCharactersForPlayer(Player player)
   bei GTA_RP.PlayerManager.HandlePlayerLogin(Client player, String password)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bei GrandTheftMultiplayer.Server.Models.ScriptingEngine.<>c__DisplayClass22_0.<InvokeVoidMethod>b__0()
   bei GrandTheftMultiplayer.Server.Models.ScriptingEngine.MainThreadLoop()

**Comment by sjlehtonen** [comment]
Try to empty the "items" table because it seems it has something to do with that.

**Comment by KriZZeL** [comment]
Thanks :)  now it´s work and what can a police officer do now after he is whitelisted?

**Comment by sjlehtonen** [comment]
Currently police officer can arrest characters assuming they are at the correct point (marked on map). I am still making the police faction but I plan to add things like writing tickets etc. I am actually thinking what features does the police faction need.
