### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by eodclan** [Samppaa/GTA-RP#19]
The registration works, but after a new login nothing comes.

Server Log:
12:32:18.671 |  Info | Program | Starting... 
12:32:19.047 |  Info | ConstantData | Loaded Language de 
12:32:19.182 | Debug | GameServer | Announcing self to master server... 
12:32:19.190 |  Info | GameServer | Loading resources... 
12:32:19.228 |  Info | GameServer | Starting GTA-RP 
12:32:20.150 |  Info | GameServer | Resource GTA-RP started. 
12:32:20.150 |  Info | Program | Started! Waiting for connections. 
12:32:20.157 |  Info | Roleplay | ####Script started!#### 
12:32:20.203 |  Info | ServerAPI | Spawned fishpoint! 
12:32:20.203 |  Info | ServerAPI | Spawned fishpoint! 
12:32:20.205 |  Info | ServerAPI | [Factions] Initialized faction "Civilian" 
12:32:20.205 |  Info | ServerAPI | [Factions] Initialized faction "Law enforcement" 
12:32:20.210 |  Info | ServerAPI | [Factions] Initialized faction "Fire department" 
12:32:20.210 |  Info | ServerAPI | [Factions] Initialized faction "First responder" 
12:32:20.212 |  Info | Roleplay | ####Script load complete!#### 
12:32:25.580 |  Info | GameServer | Initiating connection: [xxxx:60693] 
12:32:25.784 |  Info | GameServer | Processing connection: blabla (John_Striker) [xxx] 
12:32:25.953 |  Info | GameServer | Connection established: blabla (John_Striker) [xxx]

**Comment by Samppaa** [comment]
Use /login [password] to login to the server

**Comment by eodclan** [comment]
ok, thanks you.
