### ISSUE TITLE
Buying Donut

### ISSUE THREAD

**Issue by KriZZeL** [Samppaa/GTA-RP#21]
Hey :D thx for the Update greate work but i have an error from an clientside script if i buy a Donut.... i can use the Donut but is there an Animation or why i get an javascript error for the Clientside?

**Comment by sjlehtonen** [comment]
This error is fixed on the next update and it's not related to the animation. I didn't implement the donut eating animation yet because it takes some time to find the correct animations and item positions etc, I will try to do it later.
