### ISSUE TITLE
Issue with login

### ISSUE THREAD

**Issue by DioneB** [Samppaa/GTA-RP#22]
When i try the command /login test123 . the chat return "no account found with your name, but my nickname on GTMP is Test, and ai try adding another account in dabase with my current nickname, and return same error
![image](https://user-images.githubusercontent.com/15141090/36939691-f9ffc948-1f13-11e8-8a1a-fd6d5e58ba8d.png)
![image](https://user-images.githubusercontent.com/15141090/36939693-01aeebec-1f14-11e8-8457-6c9f49da6e67.png)
![image](https://user-images.githubusercontent.com/15141090/36939699-1f40c252-1f14-11e8-82e7-f958636f5386.png)

**Comment by sjlehtonen** [comment]
You have to change your username in GT-MP client. Settings -> Game settings -> Display name

Actually, it seems you have also enabled some other script that has the /login command and it overrides this game mode. Disable all other game modes except the GTA-RP

**Comment by DioneB** [comment]
tks, i think is the resource src="admin". i remove them and works fine
