### ISSUE TITLE
GetID for new Scripts

### ISSUE THREAD

**Issue by RoxiiCz** [Samppaa/GTA-RP#24]
Is there any Way to get the Player ID in new Scripts? 

I try to make a Banksystem ive Added the Bankmoney to the Database at Characters and have done some Publics in the PlayerManager for TakeBankMoney TakeMoney GiveMoney and GiveBankMoney. 

And Now i try to TriggerClientEvent if Player Stands before an ATM. When Player choose Withdraw i Need to Trigger TakeBankMoney nur i have no GetIDbyName LG something. 

Hope anyone understands my Problem and someone can help me.

**Comment by sjlehtonen** [comment]
I think you should use the Checkpoint class to do it by creating a new checkpoint like this:

`Checkpoint checkpoint = new Checkpoint(new Vector3(xPos, yPos, zPos), this.CharacterEnteredSpot, this.CharacterExitedSpot, 1, 2.0f, 66, 179, 244);
`
Now you create the methods this.CharacterEnteredSpot and this.CharacterExitedSpot like this
```
public void CharacterEnteredSpot(Checkpoint spot, Character character)
{
     character.TriggerEvent("EVENT_ENTERED_ATM_SPOT");
}
```
You can find example for Checkpoint in FishingZone.cs

Now when player clicks the withdraw then you need to send an event to the server with the money amount. Look at the EventHandler.cs for that.

**Comment by RoxiiCz** [comment]
Thanks for your Help ATMs + Banksystem Done and everything is working included Database Save

BTW: Thanks for this Script its pretty nice and easy to understand. Good Job

**Comment by Wolkefear** [comment]
hi there ! first much thanks for that script  @Samppaa we are playing it in our small community  so we are still searching for new updates  ,. my question to @RoxiiCz is it possible to share the "atm & banksystem" 
we re looking for every stuff that work with this scripts for better roleplay on our server 

*have a nice day

**Comment by RoxiiCz** [comment]
Its hard to share because i've implemented all Functions to the existing Scripts

**Comment by Wolkefear** [comment]
ah ok i understand .. thx :)  gl hf with your project m8

**Comment by sjlehtonen** [comment]
I will make the bank system and incorporate it in the script when I have time.
