### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by tibianfs** [Samppaa/GTA-RP#3]
I see this when click "Accept" on character creator menu:
`13:11:30.232 |  Info | ServerAPI | Player added to character selector! 
13:11:30.352 |  Info | ServerAPI | There are 295 models 
13:11:44.764 | Error | ScriptingEngine | EXCEPTION IN RESOURCE GTA-RP INSIDE SCRIPTENGINE EventHandler System.IndexOutOfRangeException: Indeks wykracza poza granice tablicy.
   w GTA_RP.Events.EventHandler.HandleEvent(Client player, String eventName, Object[] arguments)
   w GrandTheftMultiplayer.Server.Models.ScriptingEngine.<>c__DisplayClass58_0.<InvokeClientEvent>b__0()
   w GrandTheftMultiplayer.Server.Models.ScriptingEngine.MainThreadLoop()`

**Comment by sjlehtonen** [comment]
Hi, use the new gta_rp.sql file that I updated in the repository. It should solve the problem.

**Comment by tibianfs** [comment]
Work!

Thanks for fast reply. Your project is pro!
