### ISSUE TITLE
Cant Login 

### ISSUE THREAD

**Issue by Yarewyr** [Samppaa/GTA-RP#30]
After Register i can play but after logout i cant login again its just says no account exist with this user name but i dont get the register menu again

**Comment by sjlehtonen** [comment]
You should check that you don't have any other gamemode active that uses the "/login" command. Only have the GTA-RP active

**Comment by Yarewyr** [comment]
okay got it to work but how about Admin level which is the max and how can i use the commands? and which commands

**Comment by KriZZeL** [comment]
i tryed the 4th level and i had all permissions i need
