### ISSUE TITLE
Cant Login

### ISSUE THREAD

**Issue by thefuell** [Samppaa/GTA-RP#33]
Hey, 
first Thing u did a very awesome Job!
i registered a Player but i cannot Login when im disconnected i see the GTA V World but no window for reconnect? 

I use the open-beta launcher :)

Best wishes!

**Comment by Teixi-dev** [comment]
Try to use /login [Password]

**Comment by thefuell** [comment]
works perfect :3 thanks so much! is there any possiblities to create a Windows like for the Registration?

**Comment by Teixi-dev** [comment]
https://gt-mp.net/forum/thread/987-the-godfather-converted-to-gt-mp/
