### ISSUE TITLE
/duty didn´t work

### ISSUE THREAD

**Issue by KriZZeL** [Samppaa/GTA-RP#34]
Hello i gave me the Rank Police (Law Enforcement) and saw the /duty command but it don´t work....
i´m whitelisted on my Mysql Server and the Game show´s as job for my Charakter that i´m an Officer 
do i have to give me a rank? or is the command unfinished?

**Comment by sjlehtonen** [comment]
Hi, it's not totally implemented yet. I was on holiday for a few weeks and I'll start working on it soon again.
