### ISSUE TITLE
Error MySql DateBase

### ISSUE THREAD

**Issue by TIGIEVDK** [Samppaa/GTA-RP#39]
![default](https://user-images.githubusercontent.com/41104146/42554246-79162690-8527-11e8-9c40-0b91bbe24fae.PNG)
![default](https://user-images.githubusercontent.com/41104146/42554323-c3360d08-8527-11e8-94fa-c97458fba802.PNG)
Help fix the error: Error CS0103 the name "ConfigManager" does not exist in the current context.

**Comment by sjlehtonen** [comment]
I tested it today, it should work perfectly. You can try pulling the source again.

**Comment by TIGIEVDK** [comment]
I fixed it on the first day.
You have discord?
