### ISSUE TITLE
System.Data.dll

### ISSUE THREAD

**Issue by spyrox3** [Samppaa/GTA-RP#4]
I need the System.Data.dll for GT-MP, but i dont have it, where can i find it? thanks!

**Comment by sjlehtonen** [comment]
Should be at C:/Program files(x86)/Reference Assemblies/Microsoft/Framework/.NETFramework/v4.5

**Comment by andrewmunro** [comment]
I found that I didn't need to include this, perhaps because it's already required by the server?

https://github.com/Milkshake-Inc/GTA-RP/blob/e601951693c0b028431178765c1d281b390ddd82/docker-compose.yml#L28
