### ISSUE TITLE
Problem with second login

### ISSUE THREAD

**Issue by ChristophMarti** [Samppaa/GTA-RP#41]
Hello

Thanks for this amazing script. The script works perfectly when I'm login and register the first time. After logout there's not longer a login screen and I have to remove my account from mysql. Then it works but all dates are away. What can I do?

Thank you

Best regards
Christoph Marti

**Comment by sjlehtonen** [comment]
Use /login "password"

I haven't made the login screen yet.

**Comment by TIGIEVDK** [comment]
Can I contact you via discord?
