### ISSUE TITLE
DBManager - IniParser

### ISSUE THREAD

**Issue by ghost** [Samppaa/GTA-RP#5]
Hello,

I've a trouble with DBManager.cs

Check the screenshot but sorry he was in french ...

https://i.gyazo.com/d0c4588019d943154f2b218c14ead5cd.png

With google translate : 
" Type or namespace name 'Model' does not exist in the 'IniParser' namespace (is an assembly reference missing?) "

Thanks in advance,
Own

**Comment by sjlehtonen** [comment]
Are you sure you have all the required DLL files in your Gta server folder including the INIFileParser.dll?

**Comment by ghost** [comment]
Yeah but maybe I do not have the latest version
Can you upload the dll please?

**Comment by ghost** [comment]
I've update my INIFileParser.dll ans my System.data.dll

Here my DLL : 
[GT-MP-Server_DLL.zip](https://github.com/Samppaa/GTA-RP/files/1618498/GT-MP-Server_DLL.zip)


but i've other logs : 
https://hastebin.com/punujawige.pas

**Comment by sjlehtonen** [comment]
Did you create the Config folder with the "Config.ini" file in it?

**Comment by ghost** [comment]
Yea,

Like this? 

https://i.gyazo.com/c18f5fc9567dd3dd56fd85b2d61607a0.png

GT-MP-Server\resources\rpg\Config\Config.ini

https://hastebin.com/otisixadaw.ini

**Comment by sjlehtonen** [comment]
The "" marks are not needed, so it would be like 

```
[database]
; database configuration
server=localhost
dbname=gtarp
username=root
password=
```

**Comment by ghost** [comment]
Ok then , now i've this : https://hastebin.com/upemeyicah.scala

**Comment by sjlehtonen** [comment]
Your path is this: GT-MP-Server\resources\rpg\Config\Config.ini but it should be like GT-MP-Server\resources\GTA-RP\Config\Config.ini

**Comment by ghost** [comment]
Ok thanks :D 

Now i got this

ERROR STARTING RESOURCE rpg System.IO.FileNotFoundException: Resource does not exist.
   … GrandTheftMultiplayer.Server.GameServer.StartResource(String resourceName, String father)

**Comment by sjlehtonen** [comment]
Go to your GTA server main folder and open settings.xml, then put this `<resource src="GTA-RP"> `there and remove <resource src="rpg" /> and all other resources too.

**Comment by ghost** [comment]
ok thanks boss :D that work

Thank you very much !

See u later and nice work for your gamemode ;)
