### ISSUE TITLE
SQL file content deleted in last commit

### ISSUE THREAD

**Issue by andrewmunro** [Samppaa/GTA-RP#6]
Hey, just a heads up looks like you deleted the content of the `gta_rp.sql` file in your last commit:

https://github.com/Samppaa/GTA-RP/commit/299e774e2182d71c0280038919c75d053d3ca7c7#diff-c936cc3068f6be914bca1f3764d7cb1f

**Comment by ghost** [comment]
Hello,

For me i have clean up this commit and put gta.sql in my database : 

https://hastebin.com/ekocofuyez.sql

**Comment by sjlehtonen** [comment]
Hi, I will upload the new gta_rp.sql today with the latest commit. This one should include all the data.

**Comment by sjlehtonen** [comment]
Now the gta_rp.sql should contains the data + some sample data like characters etc.
