### ISSUE TITLE
gtarp sql

### ISSUE THREAD

**Issue by ghost** [Samppaa/GTA-RP#7]
Hello, I have a problem with the sql file, as soon as I execute the update I get this error (screen)
Would it be possible to have a file to directly create the database from a to z?

https://gyazo.com/d42e0d72ea7db8b6f4ecc34c3318fee8

**Comment by sjlehtonen** [comment]
I updated it now, I forgot to put the commands to create the tables. It's uploaded now.

**Comment by ghost** [comment]
When I log in I can not choose camp, nothing fits in the database

https://gyazo.com/c8ab83c215543f394af266774ae91195

**Comment by ghost** [comment]
I've try to create new database but i got this message : https://gyazo.com/8c13b2f50b6f1e192c866ac48133053b
That work but maybe it is important?
