### ISSUE TITLE
Launching gamemode

### ISSUE THREAD

**Issue by ghost** [Samppaa/GTA-RP#8]
Hello, 
When i start the server, i thinks any resource was loaded can you check my config?

GT-MP Server console : 
https://hastebin.com/juruvemafe.rb

Settings.xml : 
https://hastebin.com/odutihiqof.xml

Meta.xml : 
https://hastebin.com/gasomulete.xml

Server root folder
https://gyazo.com/538fbce61b58c84ee60c3c916793c58c

Resources folder 
https://gyazo.com/e2907de9468f17558d7ad991a904c5af

Thanks in advance

**Comment by ghost** [comment]
Anyone please ?

**Comment by spyrox3** [comment]
It's wrong, you have to put all you have in resources folder in one folder called GTA-RP and call it from setting.xml as a resource, then the server its gonna load that resource :)

**Comment by ghost** [comment]
Thanks bro

**Comment by ghost** [comment]
When i type
 /login test123 i got "Wrong password" or account doesnt exist
and 
/register 123 i got " An account linked to this Social Club handle already exists 

I can't create account ? and how i can log on ?

In the "readme" : 
It contains a test account with name Test and password test123

so /login test123 is right ?

**Comment by spyrox3** [comment]
Make your own account, its comes with an account and char creator

**Comment by ghost** [comment]
Ok thanks that work,
