### ISSUE TITLE
Admin commands

### ISSUE THREAD

**Issue by spyrox3** [Samppaa/GTA-RP#9]
Would be amazing to add more admin commands, so we can enjoy a better administration for our server :) and they restricted only for admin, and just a question, which is the access level for admin?

**Comment by AltisCityOwn** [comment]
Hello,

Sorry but can you look issue #8 and can you help me ?

**Comment by sjlehtonen** [comment]
I will add admin commands when I have the time, but first I have to implement things like factions properly. I am have been little busy recently, so it might take some time.

**Comment by spyrox3** [comment]
I want to talk to you, can you send me steam id or something? Thanks

**Comment by sjlehtonen** [comment]
You can give your id and I add you later, I have been little busy now.

**Comment by spyrox3** [comment]
http://steamcommunity.com/id/NEWLIFEV2/

**Comment by ghost** [comment]
@Noahh21 can you add me on steam please ? http://steamcommunity.com/id/mr-own/

**Comment by spyrox3** [comment]
I added you

**Comment by ghost** [comment]
Can i teleport on the map ?

**Comment by sjlehtonen** [comment]
Yes with /tele command

**Comment by ghost** [comment]
Do you know how easily I can have aces X Y Z

**Comment by sjlehtonen** [comment]
Use /coords
